// Generate a Bacteria! scenario with Claude and validate it against the game schema before writing.
//
//   node scripts/generate.mjs --mode daily
//   node scripts/generate.mjs --mode doi --doi 10.1126/science.1195979
//
// Needs ANTHROPIC_API_KEY in the environment (GitHub Secrets in CI). The generated JSON is validated
// with the SAME validator the game runs; an invalid generation is retried once, then fails the job so a
// bad scenario never lands. Copyright/appropriateness is left to the model's own judgment by design.
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync, appendFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { validateScenario } from "./validator.mjs";
import { buildIndex } from "./build-index.mjs";
import { slug, cleanDoi, DOI_RE } from "./doi-id.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "..");
const scenDir = join(repo, "scenarios");
const defaults = JSON.parse(readFileSync(join(here, "defaults.json"), "utf8"));
const MODEL = process.env.SCENARIO_MODEL || "claude-sonnet-5";

function arg(name) { const i = process.argv.indexOf(`--${name}`); return i >= 0 ? process.argv[i + 1] : null; }
const mode = arg("mode") || "daily";
const today = new Date().toISOString().slice(0, 10);

// ---- the parameter table, straight from the game -------------------------------------------------
// Every parameter a scenario may set, with the game's OWN doc string and authoring range, generated by
// scripts/sync-params.mjs. This used to be a 45-path list with no descriptions and defaults for a
// dozen, so the model could only meaningfully move the same handful of knobs and every scenario came
// out the same ocean with a different title. game.js documents all 157 for its tuning panel; there was
// never a reason to keep them from the thing designing the level.
const PARAMS = JSON.parse(readFileSync(join(here, "params.json"), "utf8")).params;
const PARAM_GROUPS = () => {
  const groups = new Map();
  for (const [path, p] of Object.entries(PARAMS)) {
    const g = path.split(".")[0];
    if (!groups.has(g)) groups.set(g, []);
    const range = `${p.min}..${p.max}${p.integer ? ", integer" : ""}`;
    groups.get(g).push(`  ${path} [${p.default}] (${range}) — ${p.doc}`);
  }
  return [...groups].map(([g, lines]) => `${g}:\n${lines.join("\n")}`).join("\n\n");
};
// Read a default out of defaults.json by dotted path, for quoting to the model. The guide used to
// hardcode these numbers in prose and 17 of them had drifted from the game's real CFG — it was telling
// the model substrate.sizeMax defaults to 60 when the game uses 200, so even a scenario that followed
// the guide perfectly built a board with a fraction of the intended food. Deriving them means the
// prompt cannot say something the validator disagrees with.
function D(path) {
  const v = path.split(".").reduce((o, k) => (o && typeof o === "object") ? o[k] : undefined, defaults);
  if (v === undefined) throw new Error(`no default for "${path}" — defaults.json is out of date with game.js`);
  return v;
}
function schemaSpec() {
  return `Output ONE JSON object, no prose, no markdown fences. It is DATA ONLY — it cannot contain code.
It must satisfy this schema (any unknown key, out-of-range value, or new "verb" makes it INVALID):

{
  "schema": "bacteria-scenario", "version": 1,
  "meta": {
    "title": string<=80, "date": "${today}", "lesson": string<=1200 (an original summary in your own words),
    "citation": string<=300 (optional), "difficulty": "easy"|"normal"|"hard"|"extreme" (optional),
    "realWorldBasis": string<=120 (optional)
  },
  "env": { partial CFG overrides, each a dotted path from the PARAMETER TABLE below, each a NUMBER },
  "resources": [ up to 3, each { "index": 0|1|2, "label": str, "enzymeLabel": str, "color": "#rrggbb" } ],
      // index 0 = lipid/fat class, 1 = protein, 2 = carbohydrate. Re-skin only; you cannot add a 4th class.
  "particles": { id: { "label": str, "mix": [num,num,num] (>=0, over the 3 classes),
      "shape": "aggregate"|"ellipse"|"shard", "squash": 0.1..1 (ellipse only), "weight": 0..10 } },
      // Particles carry no size of their own: every particle's radius is sampled from
      // substrate.sizeMin/sizeMax in env. Set the size there, once, in PIXELS.
  "actions": { primitive: { "label": str, "color": "#rrggbb", "weight": 0..10 } },
      // primitives are EXACTLY: enzyme0, enzyme1, enzyme2, chemotaxis, antibiotic, eps, crispr, twitching.
      // You may rename/recolor/reweight them (weight 0 removes one) but NEVER invent a new primitive.
      // A "novel enzyme" is delivered by re-skinning enzyme0/1/2 (e.g. alkane hydroxylase on the lipid class).
  "organisms": { "cells": [ { "id": str, "label": str, "color": "#rrggbb",
      "genome": { "enzLvl": [int,int,int] 0..12, "chemoLevel": int, "antibiotic": int, "eps": int, "crispr": bool, "twitching": bool },
      "immigrateWeight": 0..10 } ] },
  "terrain": [  // OPTIONAL, column scenarios only — solid, fixed scenery bounding the water.
      // Sea ice overhead, sediment or a vent floor underfoot. It is NOT food: it cannot be digested,
      // it just gets in the way, which is the point. Up to 4 layers.
      { "at": "top"|"bottom", "thickness": 20..800 (px), "color": "#rrggbb", "label": str,
        "roughness": 0..1,    // 0 = a dead-flat slab; higher = an undulating surface with relief
        "porosity": 0..1,     // voids threaded THROUGH the layer — brine channels in ice, burrows in
                              // mud. This is what makes it a habitat instead of a wall: cells can
                              // swim into the pores and shelter there. 0.3-0.5 reads well.
        "poreSize": 6..200,   // scale of those voids (small = fine channels, large = caverns)
        "featureSize": 40..2000,      // horizontal scale of the surface relief
        // SPIRES — narrow vertical structures standing off the layer: black-smoker chimneys, rocky
        // pinnacles, ice keels hanging from a ceiling. roughness alone can only make rolling hills,
        // so use these when the habitat has actual towers. Omit them for a flat mud or ice sheet.
        "spires": 0..1,        // how much of the width grows one (0 = none, 0.5 = about half)
        "spireHeight": 0..800, // how far they stand off the layer, in px
        "spireWidth": 10..400 } ],  // girth: 40-70 is a slender chimney, 200 a broad pinnacle
  "column": {   // OPTIONAL — a stratified water column. Include when depth matters (surface vs deep).
    "enabled": true|false,
    "layers": [ { "depth": num (ascending, >=0), "tempC": -10..50, "salinity": 0..60, "light": 0..1, "nutrient": 0..1 } ],
    "thermocline": { "depth": num, "sharpness": 0..1 }
  }
}

Design goals: a SPECIFIC, real microbial-ecology situation with genuine educational value; a mechanically
distinct feel via env + a re-skinned enzyme; a mini-lesson that teaches the science. Prefer real organisms
and real events. The date field must be exactly "${today}".

HOW TO DESIGN THIS LEVEL — the part that matters most:
1. Decide the SITUATION first: a specific real place, organism and problem.
2. Then decide what it should FEEL like to play. Frantic? Patient? Crowded? Cold and slow? Toxic?
3. Then reach into the parameter table below and MOVE 20-30 PARAMETERS to make that feeling real.

This is the difference between a new level and a re-titled one. A scenario that only changes the
temperature, the food count and the enzyme names is the default ocean wearing a hat. The table gives
you 157 parameters with what each one does and the range to stay inside — protist speed, senses,
hunger, breeding and resistance; the whole phage lifecycle from adsorption to burst size; cell energy,
division, chemotaxis, dormancy and upkeep; enzyme reach and lifetime; and the colour of the water
itself, at noon and at midnight, which is what makes a level look like nowhere else.

Every number you move should be traceable to the biology you are depicting. A polar sea is not just
cold: the day is long, the water is dim and green-grey, particles sink slowly and persist, grazers are
sluggish, and metabolism drops with the temperature. Make the parameters say that.

Do NOT set a parameter to its default — omit it instead. Only include what you actually changed.

PARAMETER GUIDE — the handful that most affect whether the level is playable at all:
- day.lengthSec [${D("day.lengthSec")}] s/day. day.latitude [${D("day.latitude")}] (use the SITE's real latitude; higher = stronger seasonal light). day.dayOfYear [${D("day.dayOfYear")}] = season. day.startHour [${D("day.startHour")}].
- diel.tempBase [${D("diel.tempBase")}] = mean water temperature °C (use the site's real temperature). diel.tempAmp [${D("diel.tempAmp")}] = day/night swing. diel.foodFloor [${D("diel.foodFloor")}] = night food as a fraction of noon (keep >= 0.2). diel.q10 [${D("diel.q10")}].
- substrate.count [${D("substrate.count")}] = HOW MANY food particles exist. This is the single biggest control on playability. Stay within roughly half to double the default, and never below ${Math.round(D("substrate.count") * 0.7)}. A near-empty sea is not fun and not the goal.
- substrate.sizeMin [${D("substrate.sizeMin")}] and substrate.sizeMax [${D("substrate.sizeMax")}] = particle radius in SCREEN PIXELS. These are NOT micrometres and NOT real cell dimensions — a bacterium is drawn about 8 pixels wide, so a particle is TENS TO HUNDREDS of pixels across. Writing a real microbial size here (0.4, 3, 9) makes food too small to see or eat and the level is dead on arrival. Keep sizeMin >= ${Math.round(D("substrate.sizeMin") * 0.7)} and sizeMax >= ${Math.round(D("substrate.sizeMax") * 0.5)}.
- The board must hold roughly the default amount of food. Food scales with count x (mean particle radius)^2, so halving the sizes cuts it to a QUARTER even if the count is unchanged. If you shrink the particles, raise the count to compensate.
- To convey a nutrient-poor habitat, do NOT shrink the particles and do NOT starve the board. Use diel.foodFloor, substrate.lifeMin/lifeMax (food that vanishes sooner), tougher grazing (predator.count, predator.senseRange), or a founder that must work harder for the dominant resource class.
- predator.count [${D("predator.count")}] grazers. phage.greenCount [${D("phage.greenCount")}], phage.goldCount [${D("phage.goldCount")}]. cell.startEnergy [${D("cell.startEnergy")}], cell.divideThreshold [${D("cell.divideThreshold")}].

FEEDING — the founder MUST be able to eat, or the level is dead on arrival:
- There are exactly 3 food classes: index 0 = lipid/fatty, 1 = protein, 2 = carbohydrate — each digested by its own enzyme (enzyme0/enzyme1/enzyme2). A "novel enzyme" is a re-skin of one of these on its class.
- Each particle's "mix" [c0,c1,c2] sets its composition. Whatever class DOMINATES your particles, organisms.cells[0].genome.enzLvl MUST be >= 2 in that class, or the founder starves immediately. Example: 90%-class-0 oil droplets → founder enzLvl [2, x, 1].
- Always keep enzLvl[2] (carbohydrase) >= 1 — it is the universal founding enzyme.
- If you define no particles, the default mixed marine-snow set is used; then a generalist founder (enzLvl ~ [1,1,1]) is safest.

COLUMN scenarios (a stratified water column, column.enabled=true): food particles SINK toward the floor, so set substrate.count on the higher side (90-130) and make sure the founder can eat what's near it. Use a column only when depth genuinely matters (surface vs deep).

TERRAIN (column scenarios only): where the habitat has a real physical boundary, build it. Sea ice on the underside of Antarctic fast ice, sediment at the bottom of an estuary, the mineral floor of a vent field, a microbial mat's mineral crust. Give it porosity 0.3-0.5 whenever the organisms actually live INSIDE that structure — brine channels, burrows, the interstitial spaces of a sediment — because a porous layer is somewhere to shelter and forage, while a solid one is only a wall. Match the colour to the material (pale blue-white ice, dark brown mud, grey rock). Skip terrain entirely for open-water scenarios: the open ocean has no floor worth drawing.

CHEMOSYNTHESIS / CHEMOLITHOTROPHY (hydrothermal vents, cold seeps, sulfur/ammonia/nitrite oxidizers, nitrifiers, anammox): these microbes do NOT digest particles — they fix carbon using energy from a dissolved reduced chemical. Use the ENGINE PRIMITIVE, never a re-skinned digestion enzyme (breaking down a particle with "nitrate reductase" is biologically backwards):
- set "chemolithotroph": true inside the genome of the chemosynthetic organism(s);
- set column.enabled=true and add column.chemical: { "peakDepth": 0..1 (fraction of the column where the chemical is richest — a vent floor ~0.9, a redox/oxycline ~0.5), "spread": 0.05..0.3, "strength": 0.6..1, "color": "#rrggbb" }.
A chemolithotroph draws energy from the field at its depth and must stay in the plume — it needs no particle enzyme (keep its enzLvl low, e.g. [0,0,1]).

PARAMETER TABLE — every path you may set in "env", as  path [default] (range) — what it does.
Anything not listed here is NOT settable and will make the scenario invalid. Stay inside the stated
range; a value outside it is clamped, so it will not do what you intended.

${PARAM_GROUPS()}`;
}

// Force the model to return a JSON object by making it call a tool (with tool_choice). This guarantees
// structured output regardless of how chatty the model would otherwise be — no prose-parsing, no prefill
// (which claude-sonnet-5 rejects). validateScenario does the real schema enforcement afterwards.
async function modelScenario(prompt) {
  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: { "x-api-key": process.env.ANTHROPIC_API_KEY, "anthropic-version": "2023-06-01", "content-type": "application/json" },
    body: JSON.stringify({
      model: MODEL, max_tokens: 8000,
      system: "You generate scenarios for a marine-microbiology game. Return the finished scenario by calling the emit_scenario tool with the JSON object as its input.",
      tools: [{ name: "emit_scenario", description: "Emit the finished scenario as a single JSON object matching the schema in the prompt.", input_schema: { type: "object", additionalProperties: true } }],
      tool_choice: { type: "tool", name: "emit_scenario" },
      messages: [{ role: "user", content: prompt }],
    }),
  });
  if (!res.ok) throw new Error(`Anthropic API ${res.status}: ${(await res.text()).slice(0, 500)}`);
  const data = await res.json();
  const tool = (data.content || []).find((b) => b.type === "tool_use");
  if (!tool || !tool.input || typeof tool.input !== "object") {
    console.error(`[generate] no scenario tool call. stop_reason=${data.stop_reason}; block types=${(data.content || []).map((b) => b.type).join(",")}`);
    throw new Error("model did not emit a scenario object");
  }
  // The schema/version discriminators are OUR fixed envelope, not the model's to get right — stamp them
  // so a model that fumbles the boilerplate can't fail an otherwise-good scenario.
  return { ...tool.input, schema: "bacteria-scenario", version: 1 };
}
function extractJson(text) {
  const fence = text.match(/```(?:json)?\s*([\s\S]*?)```/);
  const body = fence ? fence[1] : text;
  const start = body.indexOf("{"), end = body.lastIndexOf("}");
  if (start < 0 || end < 0) throw new Error("no JSON object in model output");
  return JSON.parse(body.slice(start, end + 1));
}

// ---- DOI resolution — metadata from Crossref, abstract from whichever source has it ----------------
// The abstract is what keeps the lesson HONEST: without it the model writes from memory and invents
// paper-specific claims. Crossref often lacks abstracts, so we cascade to Europe PMC and Semantic
// Scholar (both carry abstracts for most life-science papers) before giving up.
function stripJats(s) { return typeof s === "string" ? s.replace(/<[^>]+>/g, "").replace(/\s+/g, " ").trim() : ""; }
async function tryJson(url, headers) {
  try { const r = await fetch(url, { headers }); return r.ok ? await r.json() : null; } catch { return null; }
}
async function fetchAbstract(doi) {
  const epmc = await tryJson(`https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=DOI:${encodeURIComponent(doi)}&resultType=core&format=json`);
  const a1 = epmc?.resultList?.result?.[0]?.abstractText;
  if (a1) return { text: stripJats(a1), source: "Europe PMC" };
  const s2 = await tryJson(`https://api.semanticscholar.org/graph/v1/paper/DOI:${encodeURIComponent(doi)}?fields=abstract`);
  if (s2?.abstract) return { text: stripJats(s2.abstract), source: "Semantic Scholar" };
  return { text: "", source: "" };
}
async function resolveDoi(doi) {
  const clean = cleanDoi(doi);
  if (!DOI_RE.test(clean)) throw new Error("that does not look like a DOI");
  const res = await fetch(`https://api.crossref.org/works/${encodeURIComponent(clean)}`, {
    headers: { "User-Agent": "bacteria-the-game-scenarios (mailto:noreply@cryomics.org)" },
  });
  if (!res.ok) throw new Error(`Crossref ${res.status} for ${clean}`);
  const m = (await res.json()).message;
  const year = m.published?.["date-parts"]?.[0]?.[0] || m.created?.["date-parts"]?.[0]?.[0] || "";
  const authors = (m.author || []).slice(0, 3).map((a) => a.family).filter(Boolean).join(", ");
  let abstract = stripJats(m.abstract), absSource = abstract ? "Crossref" : "";
  if (!abstract) { const f = await fetchAbstract(clean); abstract = f.text; absSource = f.source; }
  return {
    doi: clean, abstract, absSource,
    title: Array.isArray(m.title) ? m.title[0] : m.title || "",
    journal: Array.isArray(m["container-title"]) ? m["container-title"][0] : "",
    subjects: m.subject || [],
    citation: `${authors}${authors ? " " : ""}(${year}). ${Array.isArray(m.title) ? m.title[0] : ""}. doi:${clean}`.trim(),
  };
}

function archiveSummary() {
  if (!existsSync(scenDir)) return [];
  return readdirSync(scenDir).filter((f) => f.endsWith(".json")).map((f) => {
    try { const s = JSON.parse(readFileSync(join(scenDir, f), "utf8")); return `- ${s.meta?.title} (${s.meta?.realWorldBasis || ""})`; }
    catch { return null; }
  }).filter(Boolean);
}

async function buildPrompt() {
  const archive = archiveSummary();
  const novelty = archive.length ? `\n\nAlready in the library (make yours DISTINCT from these — different organism, environment, and lesson):\n${archive.join("\n")}` : "";
  if (mode === "doi") {
    const doi = arg("doi");
    if (!doi) throw new Error("--doi required in doi mode");
    const p = await resolveDoi(doi);
    console.log(`[generate] resolved ${p.doi} — abstract source: ${p.absSource || "NONE"}`);
    const grounding = p.abstract
      ? `Abstract (source: ${p.absSource}):\n${p.abstract}\n\nGround the mini-lesson STRICTLY in this abstract and title. Do NOT state any specific figure, sample count, location, organism, mechanism, or finding that is not present in the abstract above — no invented specifics. It is fine to add general, well-established textbook background about the habitat/organism type.`
      : `No abstract could be retrieved for this paper. Therefore keep the mini-lesson GENERAL: describe the habitat/organism type at a textbook level and do NOT attribute any specific claim, number, or finding to this paper. Do not fabricate details you cannot verify.`;
    return { prompt: `${schemaSpec()}\n\nBuild a scenario seeded by this scientific paper. Capture its microbial system as a playable level and teach its topic in the mini-lesson. Use this citation verbatim in meta.citation: "${p.citation}".\n\nTitle: ${p.title}\nJournal: ${p.journal}\nSubjects: ${p.subjects.join(", ")}\n${grounding}${novelty}`,
      idHint: `doi-${slug(p.doi)}`, citation: p.citation };
  }
  if (mode === "terrain") {
    // A terrain designed in the lab (base64 JSON), for which we invent a whole scenario. Validate the
    // terrain up front — wrapped in a probe scenario — so a malformed one costs zero model calls.
    const b64 = arg("terrain-b64");
    if (!b64) throw new Error("--terrain-b64 required in terrain mode");
    let terrain;
    try { terrain = JSON.parse(Buffer.from(b64, "base64").toString("utf8")); }
    catch (e) { throw new Error("terrain payload is not valid JSON: " + e.message); }
    if (!Array.isArray(terrain)) terrain = [terrain];
    const probe = { schema: "bacteria-scenario", version: 1,
      meta: { title: "probe", date: today, lesson: "probe" },
      column: { enabled: true, layers: [{ depth: 0, tempC: 6, light: 1 }, { depth: 1, tempC: 4, light: 0 }] },
      terrain };
    const check = validateScenario(probe, defaults);
    if (!check.ok) throw new Error("submitted terrain is invalid: " + check.reason);

    const desc = terrain.map((t) => {
      const bits = [`a ${t.at === "top" ? "CEILING" : "FLOOR"} layer`, `"${t.label || (t.at === "top" ? "ice" : "sediment")}"`,
        `${t.thickness}px thick`, `colour ${t.color || "unset"}`];
      if (t.porosity > 0) bits.push(`porosity ${t.porosity} (voids threaded through it — a habitat cells live inside)`);
      if (t.spires > 0 && t.spireHeight > 0) bits.push(`spires up to ${t.spireHeight}px tall (towers standing off the layer)`);
      return "- " + bits.join(", ");
    }).join("\n");

    const idHint = arg("id") || `terrain-${today}`;
    return {
      prompt: `${schemaSpec()}\n\nThe physical setting of this level is ALREADY DESIGNED and FIXED as the terrain below. Do NOT change it and do NOT output a "terrain" field — it is stamped in for you.\n\nFixed terrain:\n${desc}\n\nRead what this terrain IS and build the real microbial community that lives against it — a porous sulfide floor with spires is a hydrothermal vent field; a porous ice ceiling is polar sea ice; a soft brown floor is estuarine or lake sediment; a pale carbonate floor is a reef. Choose real organisms and a specific, faithful habitat, and teach it in the mini-lesson.\n\nYou MUST set column.enabled=true with depth layers appropriate to this setting (terrain bounds a water column). Design env, organisms, resources, actions and particles to fit.${novelty}`,
      idHint, terrain };
  }
  return { prompt: `${schemaSpec()}\n\nInvent today's scenario: pick a real, vivid microbial-ecology situation (a specific event, habitat, or organism) with strong educational value.${novelty}`, idHint: `daily-${today}` };
}

// --mock <file> feeds a canned model response instead of calling the API, so the WHOLE pipeline
// (resolve → prompt → parse → validate → write → index) is exercisable in CI without a paid key.
const mockFile = arg("mock");
async function generateOnce(prompt) {
  // mock mode reads a canned text reply (for hermetic CI); live mode gets a parsed object via tool use.
  const raw = mockFile ? extractJson(readFileSync(mockFile, "utf8")) : await modelScenario(prompt);
  const result = validateScenario(raw, defaults);
  return { raw, result };
}

(async () => {
  // --print-prompt: dump exactly what the model will be sent and stop. The prompt is assembled from
  // params.json, the archive and several blocks of guidance, so "is X actually in there?" is not a
  // question worth answering by reading the source.
  if (process.argv.includes("--print-prompt")) {
    const { prompt } = await buildPrompt();
    process.stdout.write(prompt + "\n");
    return;
  }
  if (!mockFile && !process.env.ANTHROPIC_API_KEY) { console.error("ANTHROPIC_API_KEY is not set"); process.exit(2); }
  const { prompt, idHint, terrain } = await buildPrompt();
  let { raw, result } = await generateOnce(prompt);
  if (!result.ok) {
    console.warn("first attempt invalid:", result.reason, "— retrying once");
    ({ raw, result } = await generateOnce(`${prompt}\n\nYour previous attempt was REJECTED: ${result.reason}. Fix exactly that and output the corrected JSON only.`));
  }
  if (!result.ok) { console.error("generation failed validation twice:", result.reason); process.exit(1); }

  if (!existsSync(scenDir)) mkdirSync(scenDir, { recursive: true });
  const id = slug(idHint);
  // Credit is OURS to stamp, never the model's to invent: it comes from the person who submitted the
  // paper, and it is stamped after validation passed so it cannot be what makes a scenario fail. The
  // hard sanitising happens in the endpoint that collected it and again in the game's validator.
  const credit = (arg("credit") || "").replace(/[\u0000-\u001f<>]/g, "").trim().slice(0, 40);
  if (credit) { raw.meta = { ...raw.meta, submittedBy: credit }; }

  // A terrain seed: the boundary is the submitter's, not the model's, so stamp the terrain in verbatim
  // — the model was told not to produce one. Force column mode too, because terrain only builds in a
  // water column and a scenario that shipped the terrain without it would look fine and draw nothing.
  // Then re-gate the whole thing: if forcing broke it, fail here rather than publish a dud.
  if (terrain) {
    raw.terrain = terrain;
    raw.column = (raw.column && typeof raw.column === "object") ? raw.column : {};
    raw.column.enabled = true;
    if (!Array.isArray(raw.column.layers) || raw.column.layers.length < 1) {
      raw.column.layers = [{ depth: 0, tempC: 6, light: 1 }, { depth: 1, tempC: 4, light: 0 }];
    }
    const recheck = validateScenario(raw, defaults);
    if (!recheck.ok) { console.error("terrain stamp invalidated the scenario:", recheck.reason); process.exit(1); }
  }
  writeFileSync(join(scenDir, `${id}.json`), JSON.stringify(raw, null, 2) + "\n");
  buildIndex(repo);   // rebuild index.json from the files on disk — never accumulates stale/duplicate rows

  console.log(`✓ wrote scenarios/${id}.json — "${raw.meta.title}"`);
  if (process.env.GITHUB_OUTPUT) { try { appendFileSync(process.env.GITHUB_OUTPUT, `scenario_id=${id}\n`); } catch {} }
})().catch((e) => { console.error("generate error:", e.message); process.exit(1); });
